variables:
- group: ServiceConnection-PRD1
- name: docker.imageName
  value: 'obligationregistry'
- name: acr.azureContainerRegistryName
  value: 'prdrwdinfac1401'
- name: acr.repositoryName
  value: 'obligationregistry'
- name: serviceName
  value: 'prdrwdwebwa1401'